routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginRegisterController;
use App\Http\Controllers\BukuController;
use App\Http\Controllers\FaskesController;
use App\Http\Controllers\FaskesVaksinController;
use App\Http\Controllers\KirimEmailController;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\PengajuanPengembalianController;
use App\Http\Controllers\PinjamController;
use App\Http\Controllers\RakBukuController;
use App\Http\Controllers\RiwayatController;
use App\Http\Controllers\TambahBukuController;
use App\Http\Controllers\TipeBukuController;
use App\Http\Controllers\VaksinController;
use App\Http\Controllers\UserController;
use App\Models\PengajuanPengembalian;
use App\Models\TambahBuku;
use App\Models\Vaksin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::controller(LoginRegisterController::class)->group(function() {
    Route::get('/register', 'register')->name('register');
    Route::post('/store', 'store')->name('store');
    Route::get('/', 'login')->name('login');
    Route::get('/login', 'login')->name('login');
    Route::post('/authenticate', 'authenticate')->name('authenticate');
    Route::get('/dashboard', 'dashboard')->name('dashboard');
    Route::get('/logout', 'logout')->name('logout');
});
Route::middleware(['auth', 'role:guru'])->group(function () {
    Route::resource('user', UserController::class)->middleware('auth');
    Route::resource('tipe_buku', TipeBukuController::class)->middleware('auth');
    Route::resource('rak_buku', RakBukuController::class)->middleware('auth');
    Route::resource('tambah_buku', TambahBukuController::class)->middleware('auth');
    Route::resource('riwayat', RiwayatController::class)->middleware('auth');
    Route::post('tambah_buku/addqty', [TambahBukuController::class, 'addQty'])->name('tambah_buku.addqty');
    Route::get('/pengajuan/{id}/acc', [PinjamController::class, 'acc'])->name('pengajuan.acc')->middleware('auth');
    Route::get('/kirimEmail/{id}', [KirimEmailController::class, 'index'])->name('kirimEmail');
    Route::resource('pengajuan', PengajuanPengembalianController::class)->middleware('auth');
});

Route::middleware(['auth', 'role:siswa'])->group(function () {
    Route::resource('pinjam', PinjamController::class)->middleware('auth');
    Route::put('/kembalikan_buku/{id}', [PinjamController::class, 'kembalikanBuku'])->name('kembalikan.buku');
});

app/Models/TambahBuku.php
<?php

namespace App\Models;

use App\Traits\Uuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TambahBuku extends Model
{
    use HasFactory;
    use Uuid;

    protected $fillable = [
        'uuid',
        'nm_buku',
        'pengarang',
        'penerbit',
        'photo_buku',
        'tahun_terbit',
        'expired_book',
        'tipe_id',
        'rak_id',
    ];

    public function tipe(){
        return $this->belongsTo(TipeBuku::class);
    }
    public function rak(){
        return $this->belongsTo(RakBuku::class);
    }

    public function childbooks(){
        return $this->hasMany(ChildBuku::class, 'buku_id', 'id');
    }



}

app/Http/Controllers/TambahBukuController.php
<?php

namespace App\Http\Controllers;

use App\Models\ChildBuku;
use App\Models\RakBuku;
use App\Models\TambahBuku;
use App\Models\TipeBuku;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Picqer\Barcode\BarcodeGeneratorPNG;

class TambahBukuController extends Controller
{
    public function index(Request $request)
    {
        $per = (($request->per) ? $request->per : 10);
        $page = (($request->page) ? $request->page-1 : 0);
        DB::statement('set @angka=0+'.$per*$page);
        $data = TambahBuku::with('tipe', 'rak')
            ->where('nm_buku', 'LIKE', '%' . $request->input('search') . '%')
            ->orderBy('id', 'asc')
            ->paginate($per, ['*', DB::raw('@angka  := @angka  + 1 AS angka')]);
    
        // Barcode
        // $barcodeGenerator = new BarcodeGeneratorPNG();
        
        $data->map(function($q){
            // $q->barcode .= "<img src='data:image/png;base64,".base64_encode($barcodeGenerator->getBarcode($q->kode_buku, $barcodeGenerator::TYPE_CODE_128))."' width='250'/>";
            $q->t_buku = "<button type='button' class='btn btn-primary' onclick='tambah_buku(`$q->uuid`)'>Tambah Buku</button>";
            return $q;
            $q->aksi = '<a class="btn btn-success btn-sm" href="'.route('faskes.kuota.index', $q->uuid).'">Detail Buku</a>';
            return $q;
        });

        return view('tambah_buku.index', compact('data'));
    }

    public function create()
    {
        $tipebukus = TipeBuku::all();
        $rakbukus = RakBuku::all();
        return view('tambah_buku.create', compact('tipebukus', 'rakbukus'));
    }

    public function addQty(Request $request)
    {
        $request->validate([
            'uuid' => 'required',
            'qty' => 'required',
        ]);

        $buku = TambahBuku::findByUuid($request->uuid);

        if(!isset($buku->id)){
            return redirect()->route('tambah_buku.index')->withErrors('Data Buku Tidak Ada');
        }

        for ($i=0; $i < $request->qty; $i++) { 
            ChildBuku::create([
                'kode_buku' => rand(1, 99999999999),
                'buku_id' => $buku->id,
            ]);
        }
        
        return redirect('tambah_buku')->withSuccess('Sukses Menambah Stok Buku '.$buku->nm_buku.' Sebanyak '.$request->qty);
        
    }

    public function store(Request $request)
    {
        $request->validate([
            'nm_buku' => 'required',
            'pengarang' => 'required',
            'penerbit' => 'required',
            'expired_book' => 'required',
            'tipe_id' => 'required',
            'rak_id' => 'required',
            'photo_buku' => 'required|mimes:png,jpg,jpeg',
        ]);

        $photoPath = $request->file('photo_buku')->store('images/buku', 'public');

        $nm_buku_abbrev = substr(str_replace(' ', '', strtoupper($request->input('nm_buku'))), 0, 5);
        $date_part = date('YmdHis');
        $kode_buku = $nm_buku_abbrev . $date_part;

        $data = TambahBuku::create([
            'nm_buku' => $request->input('nm_buku'),
            'pengarang' => $request->input('pengarang'),
            'expired_book' => $request->input('expired_book'),
            'penerbit' => $request->input('penerbit'),
            'tipe_id' => $request->input('tipe_id'),
            'rak_id' => $request->input('rak_id'),
            'photo_buku' => $photoPath,
        ]);

        if ($data) {
            return redirect('tambah_buku')->withSuccess('Sukses Menambah Data');
        }

        return redirect()->route('tambah_buku.create')->withErrors('Sesuatu Error Terjadi');
    }

    public function edit(string $id)
    {
        $data = TambahBuku::findByUuid($id);
        $tipebukus = TipeBuku::all();
        $rakbukus = RakBuku::all();
        return view('tambah_buku.edit', compact('data', 'tipebukus', 'rakbukus'));
    }

public function update(Request $request, string $id)
    {
        $request->validate([
            'nm_buku' => 'required',
            'pengarang' => 'required',
            'expired_book' => 'required',
            'penerbit' => 'required',
            'tipe_id' => 'required',
            'rak_id' => 'required',
            'photo_buku' => 'nullable|mimes:png,jpg,jpeg',
        ]);

        $data = TambahBuku::findByUuid($id);

        if ($request->hasFile('photo_buku')) {
            Storage::delete('public/' . $data->photo_buku); 
            $photoPath = $request->file('photo_buku')->store('images/buku', 'public');
        } else {
            $photoPath = $data->photo_buku;
        }

        if ($data->update([
            'nm_buku' => $request->input('nm_buku'),
            'pengarang' => $request->input('pengarang'),
            'expired_book' => $request->input('expired_book'),
            'penerbit' => $request->input('penerbit'),
            'tipe_id' => $request->input('tipe_id'),
            'rak_id' => $request->input('rak_id'),
            'photo_buku' => $photoPath,
        ])) {
            return redirect('tambah_buku');
        }

        return redirect()->route('tambah_buku.edit', $data)->withErrors('Sesuatu Error Terjadi');
    }

public function destroy(string $id)
    {
        $data = TambahBuku::findByUuid($id);

        if (!$data) {
            return redirect()->route('tambah_buku.index')->withErrors('Data Tidak Ada / Sudah Dihapus');
        }

        Storage::delete($data->photo_buku);

        if ($data->delete()) {
            return redirect('tambah_buku')->withSuccess('Sukses Menghapus Data');
        }

        return redirect()->route('tambah_buku.index')->withErrors('Sesuatu Error Terjadi');
    }

    public function pinjam(Request $request)
    {
        $filterKodeBuku = $request->input('kode_buku');
        $dataBuku = TambahBuku::where(function ($query) use ($filterKodeBuku) {
            if ($filterKodeBuku) {
                $query->where('kode_buku', 'LIKE', '%' . $filterKodeBuku . '%');
            }
        })
        ->orderBy('id', 'asc')
        ->paginate(10);
    
        return view('pinjam.index', compact('dataBuku', 'filterKodeBuku'));
    
    }

}
    

resources/views/tambah_buku/create.blade.php
@extends('auth.layouts')

@section('title')
    Tambah Buku
@endsection


@section('content')
        <!-- row -->
        <div class="container-fluid">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Tambah Buku</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-form">
                            <form action="{{route('tambah_buku.store')}}" method="post"  enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="mb-3 col-md-12">
                                        <div class="input-group mb-3">
                                            <span class="input-group-text">gambar buku</span>
                                            <div class="form-file">
                                                <input type="file" name="photo_buku" accept="image/png, image/jpeg" class="form-file-input form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Nama Buku</label>
                                        <input type="text" class="form-control" required placeholder="Nama Buku" name="nm_buku">
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Pengarang</label>
                                        <input type="text" class="form-control" required placeholder="Pengarang" name="pengarang">
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Penerbit</label>
                                        <input type="text" class="form-control" required placeholder="Penerbit" name="penerbit">
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Tahun Terbit</label>
                                        <input type="date" class="form-control" required placeholder="Tahun Terbit" name="tahun_terbit">
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Batas Peminjama</label>
                                        <input type="number" class="form-control" required placeholder="date" name="expired_book">
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label" for="tipe_id">Tipe Buku</label>
                                        <select class="form-control select2" name="tipe_id">
                                            <option value="" selected disabled>Pilih</option>
                                            @foreach($tipebukus as $tipebuku)
                                                <option value="{{ $tipebuku->id }}">{{ $tipebuku->tipebuku }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label" for="rak_id">Tipe Buku</label>
                                        <select class="form-control select2" name="rak_id">
                                            <option value="" selected disabled>Pilih</option>
                                            @foreach($rakbukus as $rakbuku)
                                                <option value="{{ $rakbuku->id }}">{{ $rakbuku->rakbuku }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                   
                                   
                                </div>
                                <button type="submit" class="btn btn-primary">Tambah</button>
                                <button type="button" onclick="history.back()" class="btn btn-danger">Kembali</button>

                            </form>
                        </div>
                    </div>
                </div>

        </div>
    <!--**********************************
        Content body end
    ***********************************-->




</div>

@section('js')

    <script src="{{ asset('js/custom.min.js') }}"></script>
    <script src="{{ asset('vendor/select2/js/select2.full.min.js') }}"></script>
	<script src="{{ asset('js/dlabnav-init.js') }}"></script>

    <script>
        $('.select2').select2();
    </script>

@endsection

@endsection

resources/views/tambah_buku/edit.blade.php
@extends('auth.layouts')

@section('title')
    Edit Buku
@endsection


@section('content')
        <!-- row -->
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Edit Buku</h4>
                </div>
                <div class="card-body">
                    <div class="basic-form">
                        <form action="{{ route('tambah_buku.update', $data->uuid) }}" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div class="mb-3 col-md-12">
                                    <div class="input-group mb-3">
                                        <span class="input-group-text">gambar buku</span>
                                        <div class="form-file">
                                            <input type="file" name="photo_buku" accept="image/png, image/jpeg" class="form-file-input form-control">
                                        </div> 
                                    </div>
                                    @if ($data->photo_buku)
                                    <img src="{{ asset('storage/' . $data->photo_buku) }}" alt="Book Cover" style="max-width: 200px;">
                                @endif
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label class="form-label">Nama Buku</label>
                                    <input type="text" class="form-control" required value="{{ $data->nm_buku }}" placeholder="Nama Buku" name="nm_buku">
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label class="form-label">Pengarang</label>
                                    <input type="text" class="form-control" required value="{{ $data->pengarang }}" placeholder="Pengarang" name="pengarang">
                                </div>
                                <div class="mb-3 col-md-4">
                                    <label class="form-label">Penerbit</label>
                                    <input type="text" class="form-control" required value="{{ $data->penerbit }}" placeholder="Penerbit" name="penerbit">
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label class="form-label">Batas Peminjama</label>
                                    <input type="number" class="form-control" required value="{{ $data->expired_book }}" placeholder="date" name="expired_book">
                                </div>
                                {{-- <div class="mb-3 col-md-4">
                                    <label class="form-label">Kode Buku</label>
                                    <input type="text" class="form-control" value="{{ $data->kode_buku }}" placeholder="Kode Buku" name="kode_buku" disabled>
                                </div> --}}
                                <div class="mb-3 col-md-4">
                                    <label class="form-label">Tahun Terbit</label>
                                    <input type="date" class="form-control" required value="{{ $data->tahun_terbit }}" placeholder="Tahun Terbit" name="tahun_terbit">
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label class="form-label" for="tipe_id">Tipe Buku</label>
                                    <select class="form-control select2" name="tipe_id">
                                        @foreach($tipebukus as $tipebuku)
                                            <option value="{{ $tipebuku->id }}" {{ $tipebuku->id === $data->tipe_id ? 'selected' : '' }}>
                                                {{ $tipebuku->tipebuku }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label class="form-label" for="rak_id">Rak Buku</label>
                                    <select class="form-control select2" name="rak_id">
                                        @foreach($rakbukus as $rakbuku)
                                            <option value="{{ $rakbuku->id }}" {{ $rakbuku->id === $data->rak_id ? 'selected' : '' }}>
                                                {{ $rakbuku->rakbuku }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Update</button>
                            <button type="button" onclick="history.back()" class="btn btn-danger">Kembali</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <!--**********************************
        Content body end
    ***********************************-->




</div>

@section('js')

    <script src="{{ asset('js/custom.min.js') }}"></script>
	<script src="{{ asset('js/dlabnav-init.js') }}"></script>
    <script src="{{ asset('vendor/select2/js/select2.full.min.js') }}"></script>

    <script>
        $('.select2').select2();
    </script>

@endsection

@endsection

resources/views/tambah_buku/index.blade.php
@extends('auth.layouts')

@section('title')
    Data Buku
@endsection

@section('content')
    <!-- Modal -->
<div class="modal fade" id="tb" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Tambah Jumlah Buku</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{{route('tambah_buku.addqty')}}" method="post">
                @csrf
                <input type="hidden" name="uuid" id="uuid">
                <div class="row">
                    <div class="col-8">
                        <input class="form-control" required name="qty" id="qty" placeholder="Masukan Jumlah Buku Yang Akan Ditambahkan" min="0"/>
                    </input>
                </div>
                <div class="col-2">
                    <button class="btn btn-primary" type="submit">Tambah</button>
                </div>
            </div>
        </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

    <!-- row -->
    <div class="container-fluid">
        @php
            $key = [
                'No' => ['label' => 'angka', 'width' => 50], 
                'Nama Buku' => ['label' => 'nm_buku'],  
                'Tambah Buku' => ['label' => 't_buku'],  
                // 'Jumlah Buku' => ['label' => 'j_buku'],  
                // 'Barcode' => ['label' => 'barcode'],   
    ];
        @endphp
        <x-paginate :data="$data" :key="$key"></x-paginate>
    </div>
@endsection

@section('js')
    <script src="{{ asset('js/custom.min.js') }}"></script>
    <script src="{{ asset('js/dlabnav-init.js') }}"></script>


    <script>
        function tambah_buku(uuid){
            console.log(uuid);
            $('#uuid').val(uuid);
            $('#qty').val(0);
            $("#tb").modal('show');
        }
    </script>
@endsection