routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginRegisterController;
use App\Http\Controllers\BukuController;
use App\Http\Controllers\FaskesController;
use App\Http\Controllers\FaskesVaksinController;
use App\Http\Controllers\KirimEmailController;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\PengajuanPengembalianController;
use App\Http\Controllers\PinjamController;
use App\Http\Controllers\RakBukuController;
use App\Http\Controllers\RiwayatController;
use App\Http\Controllers\TambahBukuController;
use App\Http\Controllers\TipeBukuController;
use App\Http\Controllers\VaksinController;
use App\Http\Controllers\UserController;
use App\Models\PengajuanPengembalian;
use App\Models\TambahBuku;
use App\Models\Vaksin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::controller(LoginRegisterController::class)->group(function() {
    Route::get('/register', 'register')->name('register');
    Route::post('/store', 'store')->name('store');
    Route::get('/', 'login')->name('login');
    Route::get('/login', 'login')->name('login');
    Route::post('/authenticate', 'authenticate')->name('authenticate');
    Route::get('/dashboard', 'dashboard')->name('dashboard');
    Route::get('/logout', 'logout')->name('logout');
});
Route::middleware(['auth', 'role:guru'])->group(function () {
    Route::resource('user', UserController::class)->middleware('auth');
    Route::resource('tipe_buku', TipeBukuController::class)->middleware('auth');
    Route::resource('rak_buku', RakBukuController::class)->middleware('auth');
    Route::resource('tambah_buku', TambahBukuController::class)->middleware('auth');
    Route::resource('riwayat', RiwayatController::class)->middleware('auth');
    Route::post('tambah_buku/addqty', [TambahBukuController::class, 'addQty'])->name('tambah_buku.addqty');
    Route::get('/pengajuan/{id}/acc', [PinjamController::class, 'acc'])->name('pengajuan.acc')->middleware('auth');
    Route::get('/kirimEmail/{id}', [KirimEmailController::class, 'index'])->name('kirimEmail');
    Route::resource('pengajuan', PengajuanPengembalianController::class)->middleware('auth');
});

Route::middleware(['auth', 'role:siswa'])->group(function () {
    Route::resource('pinjam', PinjamController::class)->middleware('auth');
    Route::put('/kembalikan_buku/{id}', [PinjamController::class, 'kembalikanBuku'])->name('kembalikan.buku');
});

app/Models/RakBuku.php
<?php

namespace App\Models;

use App\Traits\Uuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RakBuku extends Model
{
    use HasFactory;
    use Uuid;

    protected $fillable = [
        'uuid',
        'rakbuku' 
    ];
}

app/Http/Controllers/RakBukuController.php
<?php

namespace App\Http\Controllers;

use App\Models\RakBuku;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class RakBukuController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $per = (($request->per) ? $request->per : 10);
        $page = (($request->page) ? $request->page-1 : 0);
        DB::statement('set @angka=0+'.$per*$page);
        $data = RakBuku::where(function($q) use ($request) {
            $q->where('rakbuku', 'LIKE', '%'.$request->search.'%');
        })->orderBy('id','asc')->paginate($per, ['*', DB::raw('@angka  := @angka  + 1 AS angka')]);

        return view('rak_buku.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('rak_buku.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'rakbuku' => 'required|string|max:250',
        ]);

        $data = RakBuku::create([
            'rakbuku' => $request->rakbuku,
        ]);

        if($data){
            return redirect()->route('rak_buku.index')->withSuccess('Sukses Menambah data');
        }

        return view('rak_buku.create')->with('error', 'Sesuatu Error Terjadi');


    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $data = RakBuku::get();

        return $data;
    }
    public function get()
    {
        $data = RakBuku::get();
        return $data;
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = RakBuku::findByUuid($id);

        return view('rak_buku.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'rakbuku' => 'required|string|max:250',
        ]);

        $data = RakBuku::findByUuid($id);


        if($data->update([
            'rakbuku' => $request->rakbuku,
        ])){
            return redirect()->route('rak_buku.index')->withSuccess('Sukses Mengubah data');
        }

        return redirect()->route('rak_buku.edit', $data)->withErrors('Sesuatu Error Terjadi');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data = RakBuku::findByUuid($id);

        if(!isset($data->id)){
            return redirect()->route('rak_buku.index')->withErrors('Data Tidak Ada / Sudah Dihapus');
        }
        if($data->delete()){
            return redirect()->route('rak_buku.index')->withSuccess('Sukses Menghapus Data');
        }

        return redirect()->route('rak_buku.index')->withErrors('Sesuatu Error Terjadi');
    }
}

resources/views/rak_buku/create.blade.php
@extends('auth.layouts')

@section('title')
    Tambah Rak Buku
@endsection


@section('content')
        <!-- row -->
        <div class="container-fluid">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Tambah Rak Buku</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-form">
                            <form action="{{route('rak_buku.store')}}" method="post"  enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Rak Buku</label>
                                        <input type="text" class="form-control" required placeholder="Rak Buku" name="rakbuku">
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Tambah</button>
                                <button type="button" onclick="history.back()" class="btn btn-danger">Kembali</button>

                            </form>
                        </div>
                    </div>
                </div>

        </div>
    <!--**********************************
        Content body end
    ***********************************-->




</div>

@section('js')

    <script src="{{ asset('js/custom.min.js') }}"></script>
	<script src="{{ asset('js/dlabnav-init.js') }}"></script>

@endsection

@endsection

resources/views/rak_buku/edit.blade.php
@extends('auth.layouts')

@section('title')
    Edit Rak Buku
@endsection


@section('content')
        <!-- row -->
        <div class="container-fluid">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Edit Rak buku</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-form">
                            <form action="{{route('rak_buku.update', $data->uuid)}}" method="post"  enctype="multipart/form-data">
                                @method('PUT')
                                @csrf
                                <div class="row">
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Rak Buku</label>
                                        <input type="text" class="form-control" required placeholder="Rak buku" name="rakbuku" value="{{$data->rakbuku}}">
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Update</button>
                                <button type="button" onclick="history.back()" class="btn btn-danger">Kembali</button>

                            </form>
                        </div>
                    </div>
                </div>
        </div>
    <!--**********************************
        Content body end
    ***********************************-->




</div>

@section('js')

    <script src="{{ asset('js/custom.min.js') }}"></script>
	<script src="{{ asset('js/dlabnav-init.js') }}"></script>

@endsection

@endsection

resources/views/rak_buku/index.blade.php
@extends('auth.layouts')

@section('title')
    Rak Buku
@endsection


@section('content')
        <!-- row -->
        <div class="container-fluid">
            @php
                $key = [
                    'No' => ['label'=>'angka', 'width'=>50], 
                    'Rak Buku' => ['label' => 'rakbuku'],  
                ];
            @endphp
            <x-paginate :data="$data" :key="$key"></x-paginate>
        </div>




</div>

@section('js')

    <script src="{{ asset('js/custom.min.js') }}"></script>
	<script src="{{ asset('js/dlabnav-init.js') }}"></script>

@endsection

@endsection