routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginRegisterController;
use App\Http\Controllers\BukuController;
use App\Http\Controllers\FaskesController;
use App\Http\Controllers\FaskesVaksinController;
use App\Http\Controllers\KirimEmailController;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\PengajuanPengembalianController;
use App\Http\Controllers\PinjamController;
use App\Http\Controllers\RakBukuController;
use App\Http\Controllers\RiwayatController;
use App\Http\Controllers\TambahBukuController;
use App\Http\Controllers\TipeBukuController;
use App\Http\Controllers\VaksinController;
use App\Http\Controllers\UserController;
use App\Models\PengajuanPengembalian;
use App\Models\TambahBuku;
use App\Models\Vaksin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::controller(LoginRegisterController::class)->group(function() {
    Route::get('/register', 'register')->name('register');
    Route::post('/store', 'store')->name('store');
    Route::get('/', 'login')->name('login');
    Route::get('/login', 'login')->name('login');
    Route::post('/authenticate', 'authenticate')->name('authenticate');
    Route::get('/dashboard', 'dashboard')->name('dashboard');
    Route::get('/logout', 'logout')->name('logout');
});
Route::middleware(['auth', 'role:guru'])->group(function () {
    Route::resource('user', UserController::class)->middleware('auth');
    Route::resource('tipe_buku', TipeBukuController::class)->middleware('auth');
    Route::resource('rak_buku', RakBukuController::class)->middleware('auth');
    Route::resource('tambah_buku', TambahBukuController::class)->middleware('auth');
    Route::resource('riwayat', RiwayatController::class)->middleware('auth');
    Route::post('tambah_buku/addqty', [TambahBukuController::class, 'addQty'])->name('tambah_buku.addqty');
    Route::get('/pengajuan/{id}/acc', [PinjamController::class, 'acc'])->name('pengajuan.acc')->middleware('auth');
    Route::get('/kirimEmail/{id}', [KirimEmailController::class, 'index'])->name('kirimEmail');
    Route::resource('pengajuan', PengajuanPengembalianController::class)->middleware('auth');
});

Route::middleware(['auth', 'role:siswa'])->group(function () {
    Route::resource('pinjam', PinjamController::class)->middleware('auth');
    Route::put('/kembalikan_buku/{id}', [PinjamController::class, 'kembalikanBuku'])->name('kembalikan.buku');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use App\Traits\Uuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    use Uuid;


    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'uuid',
        'name',
        'role',
        'email',
        'password',
        'photo',
        'api_token'
    ];

    protected $appends = ['photo_url'];

    public function getPhotoUrlAttribute()
    {
        if(!$this->photo || !is_file(public_path('images/avatar/'.$this->photo))) {
            return asset('images/avatar/default.png');
        }
        return asset('images/avatar/'.$this->photo);
    }


    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $per = (($request->per) ? $request->per : 10);
        $page = (($request->page) ? $request->page-1 : 0);
        DB::statement('set @angka=0+'.$per*$page);
        $data = User::where(function($q) use ($request) {
            $q->where('name', 'LIKE', '%'.$request->search.'%');
            $q->orWhere('email', 'LIKE', '%'.$request->search.'%');
        })->orderBy('id','asc')->paginate($per, ['*', DB::raw('@angka  := @angka  + 1 AS angka')]);

        return view('user.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:250',
            'role' => 'required|string|max:250',
            'email' => 'required|email|max:250|unique:users',
            'password' => 'required|min:8|confirmed',
            'file' => 'required|mimes:png,jpg,jpeg'
        ]);


        $name = 'User'.time().'.'.request()->file->getClientOriginalExtension();
        request()->file->move(public_path('images/avatar'), $name);

        $request->merge(
            [
                'photo' => $name
            ]);

            // return $request;

            $data = User::create([
                'name' => $request->name,
                'email' => $request->email,
                'role' => $request->role,
                'photo' => $request->foto,
                'password' => Hash::make($request->password),
                'api_token' => hash('sha256', Str::random(60))

            ]);
            if($data){
                return redirect('user');
            }

            return redirect('user.create')->withErrors( 'Sesuatu Error Terjadi');


        }

        /**
         * Display the specified resource.
         */
        public function show(string $id)
        {
            $data = User::get();

            return $data;
        }
    public function get()
    {
        $data = User::get();

        return $data;
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = User::findByUuid($id);

        return view('user.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'name' => 'required|string|max:250',
            'role' => 'required|string|max:250',
            'email' => 'required|email|max:250',
            'file' => 'nullable|mimes:png,jpg,jpeg'
        ]);

        $data = User::findByUuid($id);

        if(isset($request->file)){
            $name = 'User'.time().'.'.request()->file->getClientOriginalExtension();
            request()->file->move(public_path('images/avatar'), $name);

            $request->merge(
                [
                    'photo' => $name
                ]);
        }


        if($data->update($request->all())){
            return redirect('user');
        }

        return redirect()->route('user.edit', $data)->withErrors('Sesuatu Error Terjadi');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data = User::findByUuid($id);

        if(!isset($data->id)){
            return redirect()->route('user.index')->withErrors('Data Tidak Ada / Sudah Dihapus');
        }

        if($data->delete()){
            return redirect('user')->withSuccess('Sukses Menghapus Data');;
        }

        return redirect()->route('user.index')->withErrors('Sesuatu Error Terjadi');
    }
}

resources/views/user/create.blade.php
@extends('auth.layouts')

@section('title')
    Tambah Pengguna
@endsection


@section('content')
        <!-- row -->
        <div class="container-fluid">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Tambah User</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-form">
                            <form action="{{route('user.store')}}" method="post"  enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Nama</label>
                                        <input type="text" class="form-control" required placeholder="Nama" name="name">
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Email</label>
                                        <input type="email" class="form-control" required placeholder="Email" name="email">
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label" for="role">Role</label>
                                        <select class="form-control" name="role">
                                            <option value="" selected disabled>Pilih</option>
                                                <option value="siswa">Siswa</option>
                                                <option value="guru">Guru</option>
                                        </select>
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Password</label>
                                        <input type="password" class="form-control" required placeholder="Password" name="password">
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Re-Password</label>
                                        <input type="password" class="form-control" required placeholder="Password" name="password_confirmation">
                                    </div>
                                    <div class="mb-3 col-md-12">
                                        <div class="input-group mb-3">
											<span class="input-group-text">Photo</span>
                                            <div class="form-file">
                                                <input type="file" name="file" accept="image/png, image/jpeg" class="form-file-input form-control">
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <button type="submit" class="btn btn-primary">Tambah</button>
                                <button type="button" onclick="history.back()" class="btn btn-danger">Kembali</button>

                            </form>
                        </div>
                    </div>
                </div>

        </div>
    <!--**********************************
        Content body end
    ***********************************-->




</div>

@section('js')

    <script src="{{ asset('js/custom.min.js') }}"></script>
	<script src="{{ asset('js/dlabnav-init.js') }}"></script>

@endsection

@endsection

resources/views/user/edit.blade.php
@extends('auth.layouts')

@section('title')
    Edit Pengguna
@endsection


@section('content')
        <!-- row -->
        <div class="container-fluid">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Edit User</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-form">
                            <form action="{{route('user.update', $data->uuid)}}" method="post"  enctype="multipart/form-data">
                                @method('PUT')
                                @csrf
                                <div class="row">
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Nama</label>
                                        <input type="text" class="form-control" required placeholder="Nama" name="name" value="{{$data->name}}">
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Email</label>
                                        <input type="email" class="form-control" required placeholder="Email" name="email" value="{{$data->email}}">
                                    </div>
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label" for="role">Role</label>
                                        <select class="form-control" name="role">
                                            <option value="" selected disabled>Pilih</option>
                                            <option value="siswa" {{ $data->role === 'siswa' ? 'selected' : '' }}>Siswa</option>
                                            <option value="guru" {{ $data->role === 'guru' ? 'selected' : '' }}>Guru</option>
                                        </select>
                                    </div>
                                    <div class="mb-3 col-md-12">
                                        <div class="input-group mb-3">
											<span class="input-group-text">Photo</span>
                                            <div class="form-file">
                                                <input type="file" name="file" accept="image/png, image/jpeg" class="form-file-input form-control">
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <button type="submit" class="btn btn-primary">Update</button>
                                <button type="button" onclick="history.back()" class="btn btn-danger">Kembali</button>

                            </form>
                        </div>
                    </div>
                </div>
        </div>
    <!--**********************************
        Content body end
    ***********************************-->




</div>

@section('js')

    <script src="{{ asset('js/custom.min.js') }}"></script>
	<script src="{{ asset('js/dlabnav-init.js') }}"></script>

@endsection

@endsection

resources/views/user/index.blade.php
@extends('auth.layouts')

@section('title')
    Pengguna
@endsection


@section('content')
        <!-- row -->
        <div class="container-fluid">
            @php
                $key = [
                    'No' => ['label'=>'angka', 'width'=>50], 
                    'Nama' => ['label' => 'name'],  
                    'Email' => ['label' => 'email'],
                    'Role' => ['label' => 'role']
                ];
            @endphp
            <x-paginate :data="$data" :key="$key"></x-paginate>
        </div>




</div>

@section('js')

    <script src="{{ asset('js/custom.min.js') }}"></script>
	<script src="{{ asset('js/dlabnav-init.js') }}"></script>

@endsection

@endsection