routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginRegisterController;
use App\Http\Controllers\BukuController;
use App\Http\Controllers\FaskesController;
use App\Http\Controllers\FaskesVaksinController;
use App\Http\Controllers\KirimEmailController;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\PengajuanPengembalianController;
use App\Http\Controllers\PinjamController;
use App\Http\Controllers\RakBukuController;
use App\Http\Controllers\RiwayatController;
use App\Http\Controllers\TambahBukuController;
use App\Http\Controllers\TipeBukuController;
use App\Http\Controllers\VaksinController;
use App\Http\Controllers\UserController;
use App\Models\PengajuanPengembalian;
use App\Models\TambahBuku;
use App\Models\Vaksin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::controller(LoginRegisterController::class)->group(function() {
    Route::get('/register', 'register')->name('register');
    Route::post('/store', 'store')->name('store');
    Route::get('/', 'login')->name('login');
    Route::get('/login', 'login')->name('login');
    Route::post('/authenticate', 'authenticate')->name('authenticate');
    Route::get('/dashboard', 'dashboard')->name('dashboard');
    Route::get('/logout', 'logout')->name('logout');
});
Route::middleware(['auth', 'role:guru'])->group(function () {
    Route::resource('user', UserController::class)->middleware('auth');
    Route::resource('tipe_buku', TipeBukuController::class)->middleware('auth');
    Route::resource('rak_buku', RakBukuController::class)->middleware('auth');
    Route::resource('tambah_buku', TambahBukuController::class)->middleware('auth');
    Route::resource('riwayat', RiwayatController::class)->middleware('auth');
    Route::post('tambah_buku/addqty', [TambahBukuController::class, 'addQty'])->name('tambah_buku.addqty');
    Route::get('/pengajuan/{id}/acc', [PinjamController::class, 'acc'])->name('pengajuan.acc')->middleware('auth');
    Route::get('/kirimEmail/{id}', [KirimEmailController::class, 'index'])->name('kirimEmail');
    Route::resource('pengajuan', PengajuanPengembalianController::class)->middleware('auth');
});

Route::middleware(['auth', 'role:siswa'])->group(function () {
    Route::resource('pinjam', PinjamController::class)->middleware('auth');
    Route::put('/kembalikan_buku/{id}', [PinjamController::class, 'kembalikanBuku'])->name('kembalikan.buku');
});

app/Models/TipeBuku.php
<?php

namespace App\Models;

use App\Traits\Uuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TipeBuku extends Model
{
    use HasFactory;
    use Uuid;

    protected $fillable = [
        'uuid',
        'tipebuku' 
    ];
}

app/Http/Controllers/TipeBukuController.php
<?php

namespace App\Http\Controllers;

use App\Models\RakBuku;
use App\Models\TipeBuku;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TipeBukuController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $per = (($request->per) ? $request->per : 10);
        $page = (($request->page) ? $request->page-1 : 0);
        DB::statement('set @angka=0+'.$per*$page);
        $data = TipeBuku::where(function($q) use ($request) {
            $q->where('tipebuku', 'LIKE', '%'.$request->search.'%');
        })->orderBy('id','asc')->paginate($per, ['*', DB::raw('@angka  := @angka  + 1 AS angka')]);

        return view('tipe_buku.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('tipe_buku.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'tipebuku' => 'required|string|max:250',
        ]);

        $data = TipeBuku::create([
            'tipebuku' => $request->tipebuku,
        ]);

        if($data){
            return redirect()->route('tipe_buku.index')->withSuccess('Sukses Menambah data');
        }

        return view('tipe_buku.create')->with('error', 'Sesuatu Error Terjadi');


    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $data = RakBuku::get();

        return $data;
    }
    public function get()
    {
        $data = TipeBuku::get();
        return $data;
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = TipeBuku::findByUuid($id);

        return view('tipe_buku.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'tipebuku' => 'required|string|max:250',
        ]);

        $data = TipeBuku::findByUuid($id);


        if($data->update([
            'tipebuku' => $request->tipebuku,
        ])){
            return redirect()->route('tipe_buku.index')->withSuccess('Sukses Mengubah data');
        }

        return redirect()->route('tipe_buku.edit', $data)->withErrors('Sesuatu Error Terjadi');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data = TipeBuku::findByUuid($id);

        if(!isset($data->id)){
            return redirect()->route('tipe_buku.index')->withErrors('Data Tidak Ada / Sudah Dihapus');
        }
        if($data->delete()){
            return redirect()->route('tipe_buku.index')->withSuccess('Sukses Menghapus Data');
        }

        return redirect()->route('tipe_buku.index')->withErrors('Sesuatu Error Terjadi');
    }
}

resources/views/tipe_buku/create.blade.php
@extends('auth.layouts')

@section('title')
    Tambah Tipe Buku
@endsection


@section('content')
        <!-- row -->
        <div class="container-fluid">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Tambah Tipe Buku</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-form">
                            <form action="{{route('tipe_buku.store')}}" method="post"  enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Tipe Buku</label>
                                        <input type="text" class="form-control" required placeholder="Tipe Buku" name="tipebuku">
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Tambah</button>
                                <button type="button" onclick="history.back()" class="btn btn-danger">Kembali</button>

                            </form>
                        </div>
                    </div>
                </div>

        </div>
    <!--**********************************
        Content body end
    ***********************************-->




</div>

@section('js')

    <script src="{{ asset('js/custom.min.js') }}"></script>
	<script src="{{ asset('js/dlabnav-init.js') }}"></script>

@endsection

@endsection

resources/views/tipe_buku/edit.blade.php
@extends('auth.layouts')

@section('title')
    Edit tipe Buku
@endsection


@section('content')
        <!-- row -->
        <div class="container-fluid">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Edit tipe buku</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-form">
                            <form action="{{route('tipe_buku.update', $data->uuid)}}" method="post"  enctype="multipart/form-data">
                                @method('PUT')
                                @csrf
                                <div class="row">
                                    <div class="mb-3 col-md-6">
                                        <label class="form-label">Tipe Buku</label>
                                        <input type="text" class="form-control" required placeholder="Tipe buku" name="tipebuku" value="{{$data->tipebuku}}">
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Update</button>
                                <button type="button" onclick="history.back()" class="btn btn-danger">Kembali</button>

                            </form>
                        </div>
                    </div>
                </div>
        </div>
    <!--**********************************
        Content body end
    ***********************************-->




</div>

@section('js')

    <script src="{{ asset('js/custom.min.js') }}"></script>
	<script src="{{ asset('js/dlabnav-init.js') }}"></script>

@endsection

@endsection

resources/views/tipe_buku/index.blade.php
@extends('auth.layouts')

@section('title')
    Tipe Buku
@endsection


@section('content')
        <!-- row -->
        <div class="container-fluid">
            @php
                $key = [
                    'No' => ['label'=>'angka', 'width'=>50], 
                    'Tipe Buku' => ['label' => 'tipebuku'],  
                ];
            @endphp
            <x-paginate :data="$data" :key="$key"></x-paginate>
        </div>




</div>

@section('js')

    <script src="{{ asset('js/custom.min.js') }}"></script>
	<script src="{{ asset('js/dlabnav-init.js') }}"></script>

@endsection

@endsection